### ISSUE TITLE
[suggestion] 카카오톡을 실행하는 기능

### ISSUE THREAD

**Issue by 1saac-k** [real21c/kakao-noadv#1]
일반적인 시나리오는 윈도우 부팅 시 카카오톡과 noadv 를 같이 실행하는 것일 텐데,
그 외에 직접 카카오톡을 실행할 때도 매번 noadv를 함께 실행해야 하는 불편함이 있습니다.
그래서 noadv를 실행하면 카톡 프로세스가 있는지 검사하고 없으면 실행해주는 기능을 넣으면 편리할 것 같습니다.
일종에 noadv가 카카오톡을 wrapping 하는 형태죠.

**Comment by real21c** [comment]
안녕하세요.
광고를 제거하는 일반적인 noadv 설정은 2가지인데요^^

1) 카카오톡 메신저의 설정에서 아래의 옵션을 확인하고, 시작프로그램에 noadv를 추가합니다.
- 윈도우 시작시 자동실행OFF
- 잠금모드로 자동로그인ON

2) 또는 수동으로 noadv 를 직접 실행하는 방법이 있는데요. noadv를 수동으로 구동해도, 카카오톡 메신저가 자동으로 실행/활성화 후, 광고를 제거해주도록 코딩이 되어 있습니다. ^^

좋은 의견 감사합니다. ^^

**Comment by 1saac-k** [comment]
아 이미 있군요.
확인해보니 한 5초정도 있다가 카카오톡이 실행되네요.
확인해주셔서 감사합니다.
